- block:
    - name: Install developer tools (tilix, xclip)
      become: true
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - tilix
        - xclip
        - stow
        - git-flow

    - name: Unzip awscli
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp
        remote_src: yes

    - name: Install awscli
      become: true
      command: /tmp/aws/install --update

    - name: Install gems (kamal, solargraph)
      shell: "source {{ ansible_user_dir }}/.asdf/asdf.sh && asdf reshim ruby && gem install {{ item }}"
      args:
        executable: "{{ ansible_user_shell }}"
      loop:
        - kamal
        - solargraph

    - name: Download 1password cli
      become: true
      get_url:
        url: https://downloads.1password.com/linux/debian/amd64/stable/1password-cli-amd64-latest.deb
        dest: /tmp/1p-cli.zip

    - name: Install 1password cli
      become: true
      apt:
        deb: /tmp/1p-cli.zip
        state: present
